---
# Metadata usage hints
# attribute: usage

abstract:               "Free-text, summary description of the content, such as an abstract. Provides additional search terms in natural language; provides important summary information for non-textual resources such as images, audio, and video"
access_restriction_notes:   "Information about access restrictions due to the nature of the information in the materials being described, such as those imposed by the donor, by the repository, or by statutory/regulatory requirements"
administrative_unit:    "The name of a sub-unit within the Holding Repository; indicates a stewardship role"
arkivo_checksum:        "-- system field - not directly editable --"
author_notes:           "Free-text note that contains information from or about the authors of the material; may include or reference corresponding author information"
conference_dates:       "Date range for conference at which a conference paper was presented"
conference_name:        "The name of a conference, meeting, or event related to the material"
contact_information:    "Contact information regarding the material (not necessarily for the author)"
content_genres:         "A more detailed sub-type refining the broader Content Type element: provides a specific characterization of the nature or style of the original content source"
content_type:           "Describes the nature and general type of the original content source (as opposed to the form of the resource); provides important context for users to inform how they can interact with the content"
contributors:           "Identifies contributors to the material; can be used very broadly if exact contributions aren't known"
copyright_date:         "The date (year) for which copyright was established  [DESCRIPTIVE/USER FACING]"
create_date:            "-- system field - not directly editable --"
creator:                "Identifies the primary Creator(s) of the material"
data_classifications:   "Provides a classification of content/data included in an object, based upon Emory IT policies; used to monitor appropriate storage of data on the Emory network"
data_collection_dates:  "Date range for when data was collected for a dataset (distinct from the date the actual dataset was created)"
data_producers:         "Identifies research groups/centers/institutes who have some overarching responsibility for the data collection (may overlap with Creator)"
data_source_notes:      "Free text note about data sources used in the material"
date_created:           "The date the material was created"
date_digitized:         "Date that the item was originally digitized (as opposed to file creation date or ingest date)"
date_issued:            "The date the material was formally released or published"
date_modified:          "-- system field - not directly editable --"
date_uploaded:          "-- system field - not directly editable --"
depositor:              "-- system field - not directly editable --"
edition:                "Indicates the specific edition of a published work which the repository object contains"
emory_ark:              "A legacy Emory-issued ark"
emory_rights_statements:    "The Emory-supplied statement describing the rights status of an object, including use and reproduction limitations based on that rights status [DESCRIPTIVE/USER FACING]"
extent:                 "The extent or measurements of the original material (vs. a surrogate)"
final_published_versions:   "A link to the final published version of a work stored in the repository"
geographic_unit:        "Lowest level of geographic aggregation covered by the dataset, e.g. village, county, region"
grant_agencies:         "Identifies agencies providing grants or funding to the material"
grant_information:      "Free-text note about associated grants or funding; may include grant numbers or other statements"
has_model:              "-- system field - not directly editable --"
head:                   "-- system field - not directly editable --"
holding_repository:     "The name of the holding Library within Emory University; indicates a stewardship role"
institution:            "The name of the owner or the steward to the original source content (either physical or born-digital): the institution who is responsible for providing access to the resource. Useful for when exporting to aggregated/external repositories. [Typically this is 'Emory University' unless we are including materials from other institutions in our repository]"
internal_rights_note:   "Any notes for staff regarding rights decision points"
isbn:                   "ISBN for a published work"
issn:                   "ISSN for a published work"
issue:                  "The issue or number associated with the material"
keywords:               "Uncontrolled keywords describing the material, often provided by content creators"
legacy_rights:          "Legacy rights information which has been migrated from prior systems"
local_call_number:      "The local call number for a physical item that has been digitized for inclusion in the repository."
modified_date:          "-- system field - not directly editable --"
notes:                  "Free-text general purpose note"
on_behalf_of:           "-- system field - not directly editable --"
other_identifiers:      "An inactive identifier used in a previous system or workflow, useful for cross-referencing in migrations; may include a number of identifier types including filenames"
owner:                  "-- system field - not directly editable --"
page_range_end:         "The start of a range of page numbers for the material within the parent object/container where it was published (i.e. page numbers of an article within a journal)"
page_range_start:       "The end of a range of page numbers for the material within the parent object/container where it was published (i.e. page numbers of an article within a journal)"
parent_title:           "The title of the parent work that the material is part of, such as an article's parent journal title, a chapter or volume's parent book title, etc."
place_of_production:    "A placename or location associated with the publication or production of the material"
primary_language:       "The language of the source content being described: applies to textual or spoken word (linguistic) content"
primary_repository_ID:  "The unique, persistent identifier for a repository object"
proxy_depositor:        "-- system field - not directly editable --"
publisher:              "The name of the entity formally publishing the work"
publisher_version:      "Version of a scholarly work that is deposited in the repository (final published, post print, pre-print)"
re_use_license:         "Provides license information to inform users of appropriate usage of an object, e.g. Creative Commons License  [DESCRIPTIVE/USER FACING]"
related_datasets:       "Datasets related to this material"
related_material_notes: "Free-text field to record citations for related material"
related_publications:   "Publications related to this material"
rights_documentation:   "Link to any policy/deed etc available"
rights_holders:         "The name of the entity that holds the rights to the material  [DESCRIPTIVE/USER FACING]"
rights_statement:       "Standardized rights statement from rightsstatements.org that can be used to communicate the copyright and re-use status of digital objects to the end users  [DESCRIPTIVE/USER FACING]"
scheduled_rights_review:    "Date indicating when a review should occur in the future, to alert content curators to review when an access restriction in a deed may be changing"
scheduled_rights_review_note:   "Provides context to content curators regarding in a contract/deed needs to be reviewed for change"
sensitive_material:     "Indicates an Emory Libraries internal determination of sensitive or objectionable material"
sensitive_material_note:    "Internal statement clarifying a determination of sensitive/objectionable material"
series_title:           "The name of a larger series that the material is a part of"
sponsor:                "Identifies a sponsor for the material produced"
staff_notes:            "Internal staff-only notes about the item; does not display to end users"
state:                  "-- system field - not directly editable --"
subject_geo:            "Controlled terms or coordinates indicating geographic locations included in the content"
subject_names:          "Controlled terms for the names of people or organizations included in the content"
subject_time_periods:   "Controlled terms or time ranges describing time periods for the content"
subject_topics:         "Controlled terms describing topics included in the content of the material"
sublocation:            "Lists the physical sublocation of an object (e.g. a box/folder for archival material); not intended to denote a physical location that changes frequently"
system_of_record_ID:    "The system identifier or record number from the canonical descriptive metadata system, used to import or sync metadata in the repository with an external source"
table_of_contents:      "A table of contents for the material"
tail:                    "-- system field - not directly editable --"
technical_note:         "Free text note providing user guidance for relevant software/technology associated with the material"
title:                  "The name of the resource being described. The title may either be transcribed from the resource itself, or it may need to be created."
transfer_engineer:      "Name of the person who digitized/reformatted the master files for the object (not necessarily the additional/supplemental files)"
uniform_title:          "The standardized version of a title, established when a work has been issued under varying names"
volume:                 "The volume indication for the material"
