inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'
        - lib/tasks/sample_data.rake

Style/FrozenStringLiteralComment:
    Enabled: false

Lint/NonLocalExitFromIterator:
  Exclude:
    - app/importers/collection_permission_ensurer.rb

Metrics/AbcSize:
  Exclude:
    - app/importers/modular_importer.rb
    - spec/system/import_langmuir_from_csv_spec.rb
    - app/importers/curate_collection_importer.rb
    - app/importers/curate_record_importer.rb
    - app/lib/metadata_details.rb

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'
        - 'config/routes.rb'
        - 'config/initializers/simple_form_bootstrap.rb'
        - 'app/controllers/catalog_controller.rb'
        - 'config/initializers/hyrax.rb'
        - app/importers/curate_collection_importer.rb
        - lib/tasks/curate_collections.rake
        - config/initializers/characterization_service.rb

Metrics/ClassLength:
    Exclude:
        - 'spec/**/*'
        - 'app/models/curate_generic_work.rb'
        - 'app/controllers/catalog_controller.rb'
        - 'app/actors/hyrax/actors/file_set_actor.rb'
        - 'app/forms/hyrax/forms/collection_form.rb'
        - app/uploaders/zizia/csv_manifest_validator.rb
        - app/presenters/hyrax/collection_presenter.rb
        - app/importers/curate_mapper.rb
        - app/importers/curate_record_importer.rb

Metrics/CyclomaticComplexity:
    Exclude:
      - app/importers/curate_record_importer.rb
      - config/prepends/custom_visibility.rb
Metrics/LineLength:
    Exclude:
        - spec/importers/curate_mapper_spec.rb
        - app/importers/curate_record_importer.rb

Metrics/MethodLength:
    Exclude:
        - app/uploaders/zizia/csv_manifest_validator.rb
        - app/importers/curate_collection_importer.rb
        - app/presenters/hyrax/curate_collection_presenter.rb
        - app/presenters/hyrax/collection_presenter.rb
        - app/importers/curate_mapper.rb
        - app/forms/hyrax/curate_generic_work_form.rb
        - app/importers/curate_record_importer.rb
        - config/prepends/custom_visibility.rb
        - app/controllers/hyrax/file_sets_controller.rb
        - app/jobs/create_work_job.rb
        - app/importers/modular_importer.rb

Layout/AlignHash:
    Exclude:
        - app/models/curate_generic_work.rb
        - app/importers/curate_record_importer.rb
        - app/forms/hyrax/curate_generic_work_form.rb

Metrics/PerceivedComplexity:
    Exclude:
      - app/importers/curate_record_importer.rb
      - app/forms/hyrax/curate_generic_work_form.rb

Layout/AlignHash:
    Exclude:
        - app/models/curate_generic_work.rb
        - app/models/file_set.rb

RSpec/ExampleLength:
    Exclude:
        - 'spec/**/*'

RSpec/MessageSpies:
    EnforcedStyle: receive

RSpec/NestedGroups:
    Exclude:
        - 'spec/controllers/hyrax/downloads_controller_spec.rb'

RSpec/InstanceVariable:
    Exclude:
        - 'spec/services/characterization_service_spec.rb'

RSpec/MessageChain:
    Exclude:
        - 'spec/services/characterization_service_spec.rb'
        - 'spec/actors/hyrax/actors/file_actor_spec.rb'
