inherit_gem:
    bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'
        - lib/tasks/sample_data.rake

Layout/HashAlignment:
    EnforcedColonStyle: table

Layout/IndentationConsistency:
    EnforcedStyle: indented_internal_methods

RSpec/MessageSpies:
    EnforcedStyle: receive

Lint/NonLocalExitFromIterator:
    Exclude:
        - app/importers/collection_permission_ensurer.rb

Metrics/AbcSize:
    Exclude:
        - app/controllers/background_jobs_controller.rb
        - app/importers/curate_collection_importer.rb
        - app/importers/curate_record_importer.rb
        - app/importers/modular_importer.rb
        - app/importers/preservation_workflow_importer.rb
        - app/indexers/curate_generic_work_indexer.rb
        - app/indexers/curate/file_set_indexer.rb
        - app/jobs/characterize_job.rb
        - app/lib/metadata_details.rb
        - spec/system/import_langmuir_from_csv_spec.rb

Metrics/BlockLength:
    Exclude:
        - app/controllers/catalog_controller.rb
        - app/importers/curate_collection_importer.rb
        - app/views/manifest/manifest.json.jbuilder
        - config/initializers/characterization_service.rb
        - config/initializers/hyrax.rb
        - config/initializers/job_io_wrapper.rb
        - config/initializers/simple_form_bootstrap.rb
        - config/routes.rb
        - lib/tasks/curate_books.rake
        - lib/tasks/curate_collections.rake
        - lib/tasks/derivatives.rake
        - spec/**/*

Metrics/ClassLength:
    Exclude:
        - 'spec/**/*'
        - 'app/models/curate_generic_work.rb'
        - 'app/controllers/catalog_controller.rb'
        - 'app/controllers/iiif_controller.rb'
        - 'app/actors/hyrax/actors/file_set_actor.rb'
        - 'app/forms/hyrax/forms/collection_form.rb'
        - app/uploaders/zizia/csv_manifest_validator.rb
        - app/presenters/hyrax/collection_presenter.rb
        - app/importers/curate_mapper.rb
        - app/importers/curate_record_importer.rb
        - app/models/solr_document.rb
        - app/indexers/curate_generic_work_indexer.rb

Metrics/CyclomaticComplexity:
    Exclude:
        - app/controllers/iiif_controller.rb
        - app/importers/curate_record_importer.rb
        - app/indexers/curate_generic_work_indexer.rb
        - app/indexers/curate/file_set_indexer.rb
        - app/jobs/characterize_job.rb
        - app/models/concerns/hydra/access_controls/visibility.rb
        - config/initializers/file_actor.rb

Layout/LineLength:
    Exclude:
        - spec/importers/curate_mapper_spec.rb
        - app/importers/curate_record_importer.rb

Metrics/MethodLength:
    Exclude:
        - app/controllers/background_jobs_controller.rb
        - app/controllers/hyrax/file_sets_controller.rb
        - app/controllers/iiif_controller.rb
        - app/forms/hyrax/curate_generic_work_form.rb
        - app/importers/curate_collection_importer.rb
        - app/importers/curate_mapper.rb
        - app/importers/curate_record_importer.rb
        - app/importers/dams_preprocessor.rb
        - app/importers/modular_importer.rb
        - app/indexers/curate_generic_work_indexer.rb
        - app/indexers/curate/file_set_indexer.rb
        - app/jobs/characterize_job.rb
        - app/jobs/create_work_job.rb
        - app/models/concerns/hydra/access_controls/visibility.rb
        - app/presenters/hyrax/collection_presenter.rb
        - app/presenters/hyrax/curate_collection_presenter.rb
        - app/uploaders/zizia/csv_manifest_validator.rb
        - spec/fixtures/manifest_output.rb
        - spec/fixtures/placeholder_manifest_output.rb
        - app/importers/dams_preprocessor.rb
        - app/models/concerns/hydra/access_controls/visibility.rb

Metrics/ModuleLength:
    Exclude:
        - app/lib/metadata_definitions.rb
        - app/models/concerns/hyrax/collection_behavior.rb

Metrics/PerceivedComplexity:
    Exclude:
        - app/importers/curate_record_importer.rb
        - app/forms/hyrax/curate_generic_work_form.rb

Metrics/ParameterLists:
    Exclude:
        - app/jobs/characterize_job.rb
        - app/jobs/manifest_persistence_job.rb
        - lib/importing_modules/file_set_methods.rb

RSpec/DescribeClass:
    Exclude:
        - 'spec/models/visibility_spec.rb'

RSpec/ExampleLength:
    Exclude:
        - 'spec/**/*'

RSpec/NestedGroups:
    Exclude:
        - 'spec/controllers/hyrax/downloads_controller_spec.rb'
        - 'spec/controllers/hyrax/file_sets_controller_spec.rb'

RSpec/InstanceVariable:
    Exclude:
        - 'spec/services/characterization_service_spec.rb'

RSpec/MessageChain:
    Exclude:
        - 'spec/services/characterization_service_spec.rb'
        - 'spec/actors/hyrax/actors/file_actor_spec.rb'
        - 'spec/system/show_file_spec.rb'
        - 'spec/jobs/file_set_clean_up_job_spec.rb'
        - 'spec/jobs/check_binaries_job_spec.rb'

RSpec/AnyInstance:
    Exclude:
        - 'spec/models/job_io_wrapper_spec.rb'
        - spec/views/manifest/manifest.json.jbuilder_spec.rb

RSpec/LetSetup:
    Exclude:
        - spec/presenters/collection_presenter_spec.rb

Naming/PredicateName:
    Exclude:
        - app/models/concerns/hydra/access_controls/access_right.rb