inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'
        - lib/tasks/sample_data.rake

Style/FrozenStringLiteralComment:
    Enabled: false

Metrics/AbcSize:
  Exclude:
    - app/importers/curate_collection_importer.rb

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'
        - 'config/routes.rb'
        - 'config/initializers/simple_form_bootstrap.rb'
        - 'app/controllers/catalog_controller.rb'
        - 'config/initializers/hyrax.rb'
        - app/importers/curate_collection_importer.rb
        - lib/tasks/curate_collections.rake

Metrics/ClassLength:
    Exclude:
        - 'spec/**/*'
        - 'app/models/curate_generic_work.rb'
        - 'app/controllers/catalog_controller.rb'
        - 'app/actors/hyrax/actors/file_set_actor.rb'
        - 'app/forms/hyrax/forms/collection_form.rb'
        - app/uploaders/zizia/csv_manifest_validator.rb

Metrics/MethodLength:
    Exclude:
        - app/uploaders/zizia/csv_manifest_validator.rb
        - app/importers/curate_collection_importer.rb
        - app/presenters/hyrax/curate_collection_presenter.rb

RSpec/ExampleLength:
    Exclude:
        - 'spec/**/*'

RSpec/MessageSpies:
    EnforcedStyle: receive
