inherit_gem:
  bixby: bixby_default.yml

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'

Style/FrozenStringLiteralComment:
    Enabled: false

Metrics/BlockLength:
    Exclude:
        - 'spec/**/*'
        - 'config/routes.rb'
        - 'config/initializers/simple_form_bootstrap.rb'
        - 'app/controllers/catalog_controller.rb'

Metrics/ClassLength:
    Exclude:
        - 'spec/**/*'
        - 'app/models/curate_generic_work.rb'
        - 'app/controllers/catalog_controller.rb'

RSpec/ExampleLength:
    Exclude:
        - 'spec/**/*'

RSpec/MessageSpies:
  Enabled: false
