inherit_gem:
    bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
    TargetRubyVersion: 3.2
    Exclude:
        - bin/**/*
        - db/**/*
        - tmp/**/*
        - vendor/**/*
        - node_modules/**/*
        - lib/tasks/sample_data.rake

Layout/HashAlignment:
    EnforcedColonStyle: table

Layout/IndentationConsistency:
    EnforcedStyle: indented_internal_methods

Layout/LineLength:
    Exclude:
        - app/importers/curate_record_importer.rb
        - spec/importers/curate_mapper_spec.rb

Lint/NonLocalExitFromIterator:
    Exclude:
        - app/importers/collection_permission_ensurer.rb

Metrics/AbcSize:
    Exclude:
        - app/controllers/background_jobs_controller.rb
        - app/importers/*
        - app/indexers/curate_generic_work_indexer.rb
        - app/indexers/curate/file_set_indexer.rb
        - app/lib/metadata_details.rb
        - config/initializers/bulkrax.rb
        - spec/system/import_langmuir_from_csv_spec.rb

Metrics/BlockLength:
    Exclude:
        - app/controllers/catalog_controller.rb
        - app/importers/curate_collection_importer.rb
        - app/views/manifest/manifest.json.jbuilder
        - config/initializers/*
        - config/routes.rb
        - lib/tasks/curate_books.rake
        - lib/tasks/curate_collections.rake
        - lib/tasks/derivatives.rake
        - lib/tasks/compile_aspace_resources.rake
        - spec/**/*

Metrics/ClassLength:
    Exclude:
        - app/actors/hyrax/actors/file_set_actor.rb
        - app/controllers/catalog_controller.rb
        - app/controllers/iiif_controller.rb
        - app/forms/hyrax/forms/collection_form.rb
        - app/importers/*
        - app/indexers/curate_generic_work_indexer.rb
        - app/models/curate_generic_work.rb
        - app/models/solr_document.rb
        - app/presenters/hyrax/collection_presenter.rb
        - app/services/aspace/api_service.rb
        # Deprecation warning: Zizia will be removed with Curate v3.
        - app/uploaders/zizia/csv_manifest_validator.rb
        - spec/**/*

Metrics/CyclomaticComplexity:
    Exclude:
        - app/controllers/iiif_controller.rb
        - app/importers/curate_record_importer.rb
        - app/importers/yellowback_preprocessor.rb
        - app/indexers/curate_generic_work_indexer.rb
        - app/indexers/curate/file_set_indexer.rb
        - app/jobs/characterize_job.rb
        - app/models/concerns/hydra/access_controls/visibility.rb
        - config/initializers/bulkrax.rb
        - config/initializers/file_actor.rb

Metrics/MethodLength:
    Exclude:
        - app/controllers/background_jobs_controller.rb
        - app/controllers/hyrax/file_sets_controller.rb
        - app/controllers/iiif_controller.rb
        - app/forms/hyrax/curate_generic_work_form.rb
        - app/importers/*
        - app/indexers/curate_generic_work_indexer.rb
        - app/indexers/curate/file_set_indexer.rb
        - app/jobs/characterize_job.rb
        - app/jobs/create_work_job.rb
        - app/models/concerns/hydra/access_controls/visibility.rb
        - app/presenters/hyrax/collection_presenter.rb
        - app/presenters/hyrax/curate_collection_presenter.rb
        - app/uploaders/zizia/csv_manifest_validator.rb
        - config/initializers/bulkrax.rb
        - spec/fixtures/manifest_output.rb
        - spec/fixtures/placeholder_manifest_output.rb

Metrics/ModuleLength:
    Exclude:
        - app/lib/metadata_definitions.rb
        - app/models/concerns/hyrax/collection_behavior.rb

Metrics/ParameterLists:
    Exclude:
        - app/importers/yellowback_preprocessor.rb
        - lib/importing_modules/file_set_methods.rb
        - app/jobs/manifest_persistence_job.rb
        - app/jobs/characterize_job.rb
        - config/initializers/collection_member_search_service_overrides.rb

Metrics/PerceivedComplexity:
    Exclude:
        - app/importers/curate_record_importer.rb
        - app/importers/yellowback_preprocessor.rb
        - app/forms/hyrax/curate_generic_work_form.rb

Naming/PredicateName:
    Exclude:
        - app/models/concerns/hydra/access_controls/access_right.rb

Rails/Exit:
    Exclude:
        - 'config/deploy.rb'

Rails/Output:
    Exclude:
        - 'config/deploy.rb'

RSpec/AnyInstance:
    Exclude:
        - spec/**/*

RSpec/DescribeClass:
    Exclude:
        - spec/models/visibility_spec.rb

RSpec/ExampleLength:
    Exclude:
        - spec/**/*

RSpec/InstanceVariable:
    Exclude:
        - spec/services/characterization_service_spec.rb

RSpec/LetSetup:
    Exclude:
        - spec/presenters/collection_presenter_spec.rb

RSpec/MessageChain:
    Exclude:
        - spec/actors/hyrax/actors/file_actor_spec.rb
        - spec/jobs/check_binaries_job_spec.rb
        - spec/jobs/file_set_clean_up_job_spec.rb
        - spec/models/job_io_wrapper_spec.rb
        - spec/services/characterization_service_spec.rb
        - spec/system/show_file_spec.rb

RSpec/MessageSpies:
    EnforcedStyle: receive

RSpec/NestedGroups:
    Exclude:
        - spec/controllers/hyrax/downloads_controller_spec.rb
        - spec/controllers/hyrax/file_sets_controller_spec.rb

Style/Alias:
    Exclude:
        - config/initializers/bulkrax.rb
