version: 2.1
orbs:
    node: circleci/node@4.9.0
    qlty-orb: qltysh/qlty-orb@0.1.1
    samvera: samvera/circleci-orb@1.0.0
jobs:
    build:
        parameters:
            ruby_version:
                type: string
                default: 2.7.4
            bundler_version:
                type: string
                default: 2.1.4
            fcrepo_version:
                type: string
                default: 4.7.5
            mariadb_version:
                type: string
                default: '10.5'
            redis_version:
                type: string
                default: '4'
            solr_port:
                type: string
                default: '8983'
            solr_version:
                type: string
                default: 7-alpine
        docker:
            - image: cimg/ruby:<< parameters.ruby_version >>-node-browsers-legacy
            - environment:
                CATALINA_OPTS: -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC
              image: samvera/fcrepo4:<< parameters.fcrepo_version >>
            - command: bin/solr -cloud -noprompt -f -p << parameters.solr_port >>
              image: solr:<< parameters.solr_version >>
            - image: cimg/redis:<< parameters.redis_version >>
            - image: cimg/mariadb:<< parameters.mariadb_version >>
        working_directory: ~/project
        parallelism: 4
        steps:
            - checkout

            - node/install:
                install-yarn: true
                install-npm: false
                node-version: "v20.15.1"

            - samvera/bundle:
                ruby_version: << parameters.ruby_version >>
                bundler_version: << parameters.bundler_version >>

            - samvera/rubocop

            - run:
                name: Get yarn version
                command: echo $(yarn --version) >> "YARN_VERSION"

            - restore_cache:
                keys:
                    - v1-yarn-{{ checksum "yarn.lock" }}-{{ checksum "YARN_VERSION" }}

            - run: yarn

            - save_cache:
                key: v1-yarn-{{ checksum "yarn.lock" }}-{{ checksum "YARN_VERSION" }}
                paths:
                    - ~/project/node_modules

            - samvera/install_solr_core

            - samvera/parallel_rspec

            - qlty-orb/coverage_publish:
                files: coverage/.resultset.json
                incomplete: true
                total_parts_count: 4

            - store_artifacts:
                path: tmp/screenshots

    coverage:
        parameters:
            ruby_version:
                type: string
                default: 2.7.4
        docker:
            - image: cimg/ruby:<< parameters.ruby_version >>
        working_directory: ~/project
        parallelism: 1
        steps:
            - qlty-orb/coverage_complete

workflows:
    version: 2
    ci:
        jobs:
            - build:
                name: rspec
            - coverage:
                name: qlty
                requires:
                    - rspec
