terms:
    - id: Emory University Archives
      term: Emory University Archives
    - id: Stuart A. Rose Manuscript, Archives, and Rare Book Library
      term: Stuart A. Rose Manuscript, Archives, and Rare Book Library