default: &defaults
  api_key: <%= ENV['HONEYBADGER_API_KEY'] %>
  endpoint: https://api.honeybadger.io
  # Replace the Socket.gethostname with Rails.env or your specific environment
  env: <%= Rails.env %>
  # You can also set a specific server name if needed
  hostname: <%= ENV['HONEYBADGER_SERVER'] || Socket.gethostname %>

breadcrumbs:
    enabled: true
