all_reading_room_ips:
  # These are fake IPs as an example and testing. In the production environment the file with the real IPs
  # will be symlinked from /shared
  # expects a space-delimited list, e.g. "1.2.3 1.2.4 1.2.5"
  rose_reading_room_ip_list: <%= %w[192.0.0.255 192.0.0.250] %>
  pitts_reading_room_ip_list: <%= %w[192.0.0.255 192.0.0.250] %>
