// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "blacklight"
import "blacklight_gallery"
import "hyrax"
import "bulkrax"
import "custom/bulkrax/datatables"
import "custom/hyrax/autocomplete/default.es6"
import "custom_hyrax_collections/editor"
import "custom/hyrax/file_manager/sorting"
import "custom/hyrax/save_work/save_work_control"
import "custom/hyrax/app"
import "custom/hyrax/thumbnail_select"
import "custom/newspaper_works/ocr_search"
import "custom/validation"
import "custom/openseadragon"
