# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  PRIMARY = 'primary'.freeze
  PRESERVATION = 'supplementary'.freeze
  SUPPLEMENTAL = 'supplementary'.freeze

  property :pcdm_use, predicate: 'http://pcdm.org/use', multiple: false do |index|
    index.as :facetable
  end

  property :file_type, predicate: 'http://purl.org/dc/elements/1.1/format', multiple: false do |index|
    index.as :facetable
  end

  def primary?
    pcdm_use == PRIMARY
  end

  def supplementary?
    !primary?
  end

  include ::Hyrax::FileSetBehavior
end
